CREATE TABLE "casa" (
	"id" smallint PRIMARY KEY DEFAULT 1 NOT NULL,
	"horario_loja" jsonb NOT NULL,
	"horario_cozinha" jsonb,
	"dias_fechados" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"duracao_vaga_minutos" integer NOT NULL,
	"limite_por_vaga" integer,
	"dias_a_frente" integer NOT NULL,
	"limiar_livre" integer NOT NULL,
	"limiar_media" integer NOT NULL,
	"aceitar_cancelamentos_site" boolean DEFAULT false NOT NULL,
	"devolver_sinal_ao_cancelar" boolean DEFAULT false NOT NULL,
	"valor_minimo_cent" integer,
	"pausa_ate" timestamp with time zone,
	"ordem_ementa" jsonb NOT NULL,
	"versao_pedidos" bigint DEFAULT 0 NOT NULL,
	"pin_equipa_hash" text,
	CONSTRAINT "casa_uma_so" CHECK ("casa"."id" = 1),
	CONSTRAINT "casa_duracao_vaga" CHECK ("casa"."duracao_vaga_minutos" between 5 and 240),
	CONSTRAINT "casa_limite_por_vaga" CHECK ("casa"."limite_por_vaga" > 0),
	CONSTRAINT "casa_dias_a_frente" CHECK ("casa"."dias_a_frente" between 0 and 365),
	CONSTRAINT "casa_limiares" CHECK ("casa"."limiar_livre" between 0 and 100 and "casa"."limiar_media" between 0 and 100 and "casa"."limiar_livre" < "casa"."limiar_media"),
	CONSTRAINT "casa_valor_minimo" CHECK ("casa"."valor_minimo_cent" >= 0)
);
--> statement-breakpoint
CREATE TABLE "produtos" (
	"id" text PRIMARY KEY NOT NULL,
	"posicao" integer NOT NULL,
	"origem" text NOT NULL,
	"familia" text NOT NULL,
	"nome_pt" text NOT NULL,
	"nome_en" text,
	"descricao_pt" text,
	"descricao_en" text,
	"carta" text,
	"categoria" text,
	"subcategoria" text,
	"unidade" text NOT NULL,
	"escolhas" text[] DEFAULT '{}' NOT NULL,
	"tempo_producao_unidade" text,
	"tempo_producao_valor" numeric,
	"quantidade_minima" numeric NOT NULL,
	"multiplo" numeric NOT NULL,
	"a_venda_online" boolean NOT NULL,
	"aparece_na_ementa" boolean NOT NULL,
	"alergenios" text[],
	"vegan" boolean DEFAULT false NOT NULL,
	"sem_gluten" boolean DEFAULT false NOT NULL,
	"fotos" text[] DEFAULT '{}' NOT NULL,
	"sinal_percent" integer,
	"limite_quantidade" integer,
	"limite_modo" text,
	"arquivado" boolean DEFAULT false NOT NULL,
	"fora_de_venda" boolean DEFAULT false NOT NULL,
	"esgotado_no_dia" date,
	CONSTRAINT "produtos_id_formato" CHECK ("produtos"."id" ~ '^[a-z0-9-]+$'),
	CONSTRAINT "produtos_origem" CHECK ("produtos"."origem" in ('ementa', 'encomendas')),
	CONSTRAINT "produtos_familia" CHECK ("produtos"."familia" in ('ementa', 'festa', 'bolo', 'box', 'medida')),
	CONSTRAINT "produtos_familia_da_origem" CHECK (("produtos"."origem" = 'ementa') = ("produtos"."familia" = 'ementa')),
	CONSTRAINT "produtos_ementa_com_carta" CHECK ("produtos"."familia" <> 'ementa' or ("produtos"."carta" is not null and "produtos"."categoria" is not null)),
	CONSTRAINT "produtos_unidade" CHECK ("produtos"."unidade" in ('un', 'kg')),
	CONSTRAINT "produtos_descricao_pt" CHECK ("produtos"."descricao_en" is null or "produtos"."descricao_pt" is not null),
	CONSTRAINT "produtos_tempo_producao_par" CHECK (("produtos"."tempo_producao_unidade" is null) = ("produtos"."tempo_producao_valor" is null)),
	CONSTRAINT "produtos_tempo_producao" CHECK ("produtos"."tempo_producao_unidade" in ('horas', 'dias') and "produtos"."tempo_producao_valor" >= 0),
	CONSTRAINT "produtos_minimo_e_multiplo" CHECK ("produtos"."quantidade_minima" > 0 and "produtos"."multiplo" > 0),
	CONSTRAINT "produtos_sinal" CHECK ("produtos"."sinal_percent" between 1 and 100),
	CONSTRAINT "produtos_limite_par" CHECK (("produtos"."limite_quantidade" is null) = ("produtos"."limite_modo" is null)),
	CONSTRAINT "produtos_limite" CHECK ("produtos"."limite_quantidade" > 0 and "produtos"."limite_modo" in ('porDia', 'total'))
);
--> statement-breakpoint
CREATE TABLE "variantes" (
	"produto_id" text NOT NULL,
	"id" text NOT NULL,
	"posicao" integer NOT NULL,
	"rotulo_pt" text,
	"rotulo_en" text,
	"pessoas" integer,
	"preco_cent" integer,
	"composicao" jsonb DEFAULT '[]'::jsonb NOT NULL,
	CONSTRAINT "variantes_produto_id_id_pk" PRIMARY KEY("produto_id","id"),
	CONSTRAINT "variantes_rotulo_pt" CHECK ("variantes"."rotulo_en" is null or "variantes"."rotulo_pt" is not null),
	CONSTRAINT "variantes_pessoas" CHECK ("variantes"."pessoas" > 0),
	CONSTRAINT "variantes_preco" CHECK ("variantes"."preco_cent" >= 0)
);
--> statement-breakpoint
ALTER TABLE "variantes" ADD CONSTRAINT "variantes_produto_id_produtos_id_fk" FOREIGN KEY ("produto_id") REFERENCES "public"."produtos"("id") ON DELETE no action ON UPDATE no action;